version: "3.9"
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    ports:
      - "5436:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "--username", "postgres", "--dbname", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # goapptest:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.golangtest
  #   depends_on:
  #     postgres:
  #       condition: service_healthy
  #   ports:
  #     - "8080:8080"

  goapp:
    build:
      context: .
      dockerfile: Dockerfile.golang
    depends_on:
      postgres:
        condition: service_healthy
      # goapptest:
      #   condition: service_completed_successfully
    ports:
      - "8080:8080"